tsirysndr/repl

git.ts
main.ts

added git plugin

---

README.md

readme: add animated terminal GIF showing usage

---

main.ts
plugins/terraform.ts

Please review and merge the PR
closes #7

Terraform plugin added

---

README.md
main.ts
plugins/pkgx.ts

feat: add plugin for `pkgx`

---

README.md
main.ts
plugins/pulumi.ts

feat: add plugin for `pulumi`

---

README.md
main.ts
plugins/tilt.ts

feat: add plugin for `tilt`

---

README.md
main.ts
plugins/spin.ts

feat: add plugin for `spin`

---

README.md
main.ts
plugins/wasmer.ts

feat: add plugin for `wasmer`

---

README.md
main.ts
plugins/dagger.ts

feat: add plugin for `dagger`

---

README.md
main.ts
plugins/bun.ts
plugins/dagger.ts
plugins/docker.ts
plugins/git.ts
plugins/github-cli.ts
plugins/helm.ts
plugins/pulumi.ts
plugins/spin.ts
plugins/tilt.ts
plugins/wasmer.ts

feat: add plugin for `helm`

---

README.md
main.ts
plugins/devbox.ts

feat: add plugin for `devbox`

---

README.md
main.ts
plugins/bazel.ts

feat: add plugin for `bazel`

---

main.ts
plugins/bazel.ts
plugins/brew.ts
plugins/bun.ts
plugins/dagger.ts
plugins/deno.ts
plugins/devbox.ts
plugins/docker.ts
plugins/git.ts
plugins/github-cli.ts
plugins/helm.ts
plugins/kubectl.ts
plugins/pkgx.ts
plugins/pulumi.ts
plugins/spin.ts
plugins/terraform.ts
plugins/tilt.ts
plugins/wasmer.ts
src/plugin.ts

feat: automatically install plugin if not already installed

---

README.md
main.ts
plugins/npm.ts

feature: Add npm plugin #21

---

README.md
main.ts
plugins/terragrunt.ts

feat: add plugin for `terragrunt`

---

README.md
main.ts
plugins/nix.ts

feat: add plugin for `nix`

---

README.md
main.ts
plugins/home-manager.ts
plugins/nix.ts

feat: add plugin for `home-manager`

---

main.ts
plugins/flakehub.ts
plugins/mod.ts

feat: add plugin for `flakehub`

---

README.md
plugins/fastlane.ts
plugins/mod.ts

feat: add plugin for `fastlane`

---

README.md
deps.ts
plugins/gulp.ts
plugins/mod.ts

feat: add plugin for `gulp`

---

README.md
plugins/flox.ts
plugins/mod.ts

feat: add plugin for `flox`

---

README.md
plugins/devenv.ts
plugins/mod.ts

feat: add plugin for `devenv`

---

README.md
plugins/mod.ts
plugins/turbo.ts

feat: add plugin for `turbo`

---

README.md
flake.lock
flake.nix
plugins/mod.ts
plugins/turso.ts

feat: add plugin for `turso`

---

README.md
plugins/mod.ts
plugins/pscale.ts

feat: add plugin for `pscale`

---

README.md
plugins/grunt.ts
plugins/mod.ts

feat: add plugin for `grunt`

---

README.md
plugins/mod.ts
plugins/rtx.ts

feat: add plugin for `rtx`

---

README.md
plugins/mod.ts
plugins/nx.ts

feat: add plugin for `nx`
